name: Daily Discord Heartbeat

on:
  schedule:
    - cron: '0 10 * * *'  # Minden nap 10:00-kor indul
  workflow_dispatch:      # Manuális indítás engedélyezése

jobs:
  heartbeat:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install discord.py==2.3.2
          pip install psutil

      - name: Run heartbeat bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: python bot.py
